// Background service worker for BobTester Recorder Extension
let isRecording = false;
let recordedActions = [];
let currentTabId = null;

// Listen for messages from content script and popup
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  console.log('[BobTester Extension] Message received:', message);

  switch (message.type) {
    case 'START_RECORDING':
      startRecording(message.url, sendResponse);
      return true; // Keep channel open for async response

    case 'STOP_RECORDING':
      stopRecording(sendResponse);
      return true;

    case 'GET_STATUS':
      sendResponse({ isRecording, actionsCount: recordedActions.length });
      break;

    case 'ACTION_RECORDED':
      if (isRecording) {
        recordedActions.push(message.action);
        console.log('[BobTester Extension] Action recorded:', message.action);
        // Broadcast to popup if open
        chrome.runtime.sendMessage({ 
          type: 'ACTIONS_UPDATED', 
          actions: recordedActions 
        }).catch(() => {}); // Ignore if popup is closed
      }
      break;

    case 'GET_RECORDED_CODE':
      const code = generatePlaywrightCode(recordedActions);
      sendResponse({ code, actions: recordedActions });
      break;

    case 'CLEAR_RECORDING':
      recordedActions = [];
      sendResponse({ success: true });
      break;

    default:
      console.warn('[BobTester Extension] Unknown message type:', message.type);
  }
});

// Listen for messages from web app
chrome.runtime.onMessageExternal.addListener((message, sender, sendResponse) => {
  console.log('[BobTester Extension] External message from:', sender.url);
  
  if (message.type === 'START_RECORDING') {
    startRecording(message.url, sendResponse);
    return true;
  } else if (message.type === 'GET_RECORDED_CODE') {
    const code = generatePlaywrightCode(recordedActions);
    sendResponse({ code, actions: recordedActions });
  }
});

async function startRecording(url, sendResponse) {
  try {
    isRecording = true;
    recordedActions = [];
    
    // Create or navigate to tab
    if (currentTabId) {
      await chrome.tabs.update(currentTabId, { url, active: true });
    } else {
      const tab = await chrome.tabs.create({ url, active: true });
      currentTabId = tab.id;
    }

    // Inject content script
    await chrome.scripting.executeScript({
      target: { tabId: currentTabId },
      files: ['content.js']
    });

    sendResponse({ success: true, message: 'Recording started' });
  } catch (error) {
    console.error('[BobTester Extension] Start recording error:', error);
    sendResponse({ success: false, error: error.message });
  }
}

function stopRecording(sendResponse) {
  isRecording = false;
  const code = generatePlaywrightCode(recordedActions);
  sendResponse({ 
    success: true, 
    code, 
    actions: recordedActions,
    message: 'Recording stopped' 
  });
}

function generatePlaywrightCode(actions) {
  if (!actions || actions.length === 0) {
    return '// No actions recorded';
  }

  let code = `// Generated by BobTester Recorder\n`;
  code += `// ${new Date().toISOString()}\n\n`;

  actions.forEach((action, index) => {
    switch (action.type) {
      case 'goto':
        code += `await page.goto('${action.url}');\n`;
        break;
      case 'click':
        code += `await page.locator('${action.selector}').click();\n`;
        break;
      case 'fill':
        code += `await page.locator('${action.selector}').fill('${action.value}');\n`;
        break;
      case 'select':
        code += `await page.locator('${action.selector}').selectOption('${action.value}');\n`;
        break;
      case 'check':
        code += `await page.locator('${action.selector}').check();\n`;
        break;
      case 'uncheck':
        code += `await page.locator('${action.selector}').uncheck();\n`;
        break;
      case 'press':
        code += `await page.locator('${action.selector}').press('${action.key}');\n`;
        break;
      default:
        code += `// Unknown action: ${action.type}\n`;
    }
  });

  return code;
}

// Clean up when tab is closed
chrome.tabs.onRemoved.addListener((tabId) => {
  if (tabId === currentTabId) {
    currentTabId = null;
    if (isRecording) {
      isRecording = false;
      console.log('[BobTester Extension] Recording stopped - tab closed');
    }
  }
});

// Made with Bob
